# title: Graficos.net
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Site Main Vars
encoding: utf-8
name: Graficos.net
description: > # this means to ignore newlines until "markdown:"
  ▶Web Designer, Front-end Dev, Agriculture Engineer. Diseño web Zaragoza. 
  Diseñador Páginas web. Developer. Responsive. WPO. Ilustrador. Ingeniero. Freelance.
twitter_username: pollobrav0
github_username:  gangsthub
email: bravo@graficos.net

# Build settings
markdown: redcarpet
highlighter: null # or rouge or pygments.rb
exclude: [ "node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock" ]


